version: '3.9'
services:
  php:
    build: ./src/php
    volumes:
      - ./src/app:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    environment:
      - PORT=8000
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/app:/var/www/html
    depends_on:
      - php
